module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar from the docs folder 
    },
    {
      type: 'link',
      label: 'Lab Guide Home', 
      href: 'https://creatorworkflowsnow.github.io/',
    },
  ],
};