module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // generate sidebar from the docs folder 
    },
    {
      type:'link',
      label:'Post Lab Survey',
      href: 'https://crewteam.service-now.com/esc?id=workshop_survey&type_id=ff8cc99e877d21106af8ec6e0ebb3546',
    },
  ],
};